version: '3.8'
services:
  mongodb:
    image: mongo:6.0.3
    volumes:
      - ./data:/data/db
    ports:
      - "27717:27017"
  mongodb-test:
    image: mongo:6.0.3
    ports:
      - "27718:27017"
volumes:
  mongodb:
    driver: local
